/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/components/**/*.{js,vue,ts}",
    "./src/layouts/**/*.vue",
    "./src/pages/**/*.vue",
    "./src/plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fef6ec',
        surface: '#fef6ec',
        'on-background': '#361002',
        'on-surface': '#361002',
        'on-primary': '#361002',
        'surface-bright': '#fef6ec',
        'surface-light': '#f6eee4',
        'surface-variant': '#4c4844',
        'on-surface-variant': '#f6eee4',
        primary: '#e9c182',
        'primary-dark': '#000000',
        secondary: '#ff93b5',
        'secondary-dark': '#d27995',
        error: '#e9340c',
        info: '#2196F3',
        success: '#58e39e',
        warning: '#ee8f30',
        black: '#000000',
        white: '#FFFFFF',
        'kbd': '#212529',
        'on-kbd': '#FFFFFF',
        'code': '#F5F5F5',
        'on-code': '#000000',
      },
      opacity: {
        'border': '0.2',
        'high-emphasis': '0.87',
        'medium-emphasis': '0.60',
        'disabled': '0.38',
        'idle': '0.04',
        'hover': '0.2',
        'focus': '0.12',
        'selected': '0.08',
        'activated': '0.12',
        'pressed': '0.12',
        'dragged': '0.08',
      }
    }
  },
  plugins: [require("tailwindcss-animate")],
}